import Vue from 'vue'
import { Button,PageHeader,Step,Radio,RadioGroup,RadioButton,Steps,Badge,Tabs,TabPane,Footer,Backtop,Carousel,CarouselItem,Upload,DatePicker,Progress,Collapse,CollapseItem,Message,MessageBox,Dialog,Pagination,Switch,Table,TableColumn,Select,Option,Form,FormItem,Input,Image,Container,Header,Aside,Main,Menu,Submenu,MenuItem,Avatar,Dropdown,DropdownMenu,DropdownItem,Breadcrumb,BreadcrumbItem,Row,Divider,Col,Card} from "element-ui";

Vue.use(Form);
Vue.use(FormItem);
Vue.use(Input);
Vue.use(Button);
Vue.use(Image);
Vue.use(Container);
Vue.use(Header);
Vue.use(Aside);
Vue.use(Main);
Vue.use(Menu);
Vue.use(Submenu);
Vue.use(MenuItem);
Vue.use(Avatar);
Vue.use(Dropdown);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Breadcrumb);
Vue.use(BreadcrumbItem);
Vue.use(Row);
Vue.use(Divider);
Vue.use(Col);
Vue.use(Card);
Vue.use(Select);
Vue.use(Option);
Vue.use(Table);
Vue.use(TableColumn);
Vue.use(Switch);
Vue.use(Pagination);
Vue.use(Dialog);
Vue.use(Collapse);
Vue.use(CollapseItem);
Vue.use(Upload);
Vue.use(Progress);
Vue.use(DatePicker);
Vue.use(Carousel);
Vue.use(CarouselItem);
Vue.use(Backtop);
Vue.use(Footer);
Vue.use(Tabs);
Vue.use(TabPane);
Vue.use(Badge);
Vue.use(Step);
Vue.use(Steps);
Vue.use(RadioButton);
Vue.use(RadioGroup);
Vue.use(Radio);
Vue.use(PageHeader);
Vue.prototype.$message = Message;
Vue.prototype.$confirm = MessageBox.confirm;